### Test API Requests
@username = daneorie

GET https://api.github.com/users/{{username}}
Accept: application/json

###

POST https://httpbin.org/post
Content-Type: application/json

{
  "name": "test",
  "value": 123
}

###

# Test with variables
@baseUrl = https://jsonplaceholder.typicode.com
@userId = 1

GET {{baseUrl}}/users/{{userId}}
Accept: application/json
